global proc shelf_blurWeightModule_DEV () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "import sys\n\nfrom mPaintEditor import PAINT_EDITOR\nif PAINT_EDITOR is not None:\n    PAINT_EDITOR.close()\n    PAINT_EDITOR.deleteLater()\n    PAINT_EDITOR = None\n    \n    todel = [m for m in sys.modules if 'mPaintEditor' in m]\n    for d in todel:\n        del sys.modules[d]\n\nfrom mPaintEditor import runMPaintEditor\nrunMPaintEditor()\n\n\n\n" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "reloadPaintEditor" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -imageOverlayLabel "reloadPaintEditor" 
        -overlayLabelColor 0.8 0.8 0.8 
        -overlayLabelBackColor 0 0 0 0.5 
        -image "pythonFamily.png" 
        -image1 "pythonFamily.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "import sys\n\nfrom mPaintEditor import PAINT_EDITOR\nif PAINT_EDITOR is not None:\n    PAINT_EDITOR.close()\n    PAINT_EDITOR.deleteLater()\n    PAINT_EDITOR = None\n    \n    todel = [m for m in sys.modules if 'mPaintEditor' in m]\n    for d in todel:\n        del sys.modules[d]\n\nfrom mPaintEditor import runMPaintEditor\nrunMPaintEditor()\n\n\n\n" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;

} 
